# Generated by Django 2.2.16 on 2022-08-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220819_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Уровень сложности',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.ForeignKey(blank=True, help_text='Укажите уровень сложности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Difficulty', verbose_name='Сложность'),
        ),
    ]
