# Generated by Django 2.2.16 on 2022-09-01 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220831_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Заголовок по умолчанию', help_text='Будьте конкретны. Представьте, что вы задаёте вопрос другому человеку.', max_length=300, verbose_name='Заголовок треда'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Добавьте всю информацию, которая может понадобиться для ответа на ваш вопрос', verbose_name='Основная часть'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.ForeignKey(blank=True, help_text='Укажите уровень сложности', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Difficulty', verbose_name='Сложность вопроса'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Добавьте метки, описывающие о чём ваш вопрос', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Group', verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Заголовок по умолчанию', help_text='Будьте конкретны. Представьте, что вы задаёте вопрос другому человеку.', max_length=300, verbose_name='Заголовок треда'),
        ),
    ]
