# Generated by Django 2.2.16 on 2022-09-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(default='Заголовок', max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='Заголовок', max_length=1000, verbose_name=''),
        ),
    ]
