# Generated by Django 2.2.16 on 2022-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20220914_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='who_needed',
            field=models.CharField(default='Кто требуется в команду?', max_length=1000, verbose_name=''),
        ),
    ]
