# Generated by Django 2.2.16 on 2022-09-15 13:12

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20220915_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='tags',
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(default='Заголовок', max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='who_needed',
            field=mdeditor.fields.MDTextField(default='Кто требуется в команду?', verbose_name='Кто нужен команде?'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='Заголовок', max_length=1000, verbose_name='Название'),
        ),
    ]
