# Generated by Django 2.2.16 on 2022-09-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20220915_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='TagIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='ideas.TagIdea', to='ideas.Tag', verbose_name='Теги'),
        ),
    ]
